### ISSUE TITLE
crud for composite primary key table

### ISSUE THREAD

**Issue by t1ina2003** [mevdschee/php-crud-api#10]
How can i do CRUD operations in composite primary key table? 
thanks in advance.

**Comment by mevdschee** [comment]
Great question, thank you. Composite primary keys are not supported.

A workaround would be to add a singular primary key (for instance named "id") and convert your primary key to an index with an unique constraint. I'm not sure this helps you.

**Comment by mevdschee** [comment]
Updated the docs, see: 8bb895c77940436867dfd110afa0e91adfd0013f

**Comment by t1ina2003** [comment]
thank for your reply~ =)
but... the exist table i'm now working on has the composite primary key. (and i can't change it)
Is there any hint for editing api.php to achieve this goal. 
It's conceivable that applying C,R,U,D to composite key is a huge project.

**Comment by mevdschee** [comment]
You would have to adjust the relation detection and matching (hard) and the primary key detection and matching (easy). In my opinion it is not worth it as indeed that is a huge project (that nobody else needs). You should really consider using surrogate keys instead of composite ones.

For a good read on the topic, see: [Composite keys are evil](http://www.codebetter.com/jeremymiller/2007/02/01/composite-keys-are-evil/)
