### ISSUE TITLE
Add filter for join

### ISSUE THREAD

**Issue by lenovin** [mevdschee/php-crud-api#1005]
Hi,

Can you add a feature like adding a filter option in join tables

Regards

**Comment by mevdschee** [comment]
Filtering based on values in joined tables is not supported. You can work around this by doing two queries or reversing the query (join in the other direction).

**Comment by mevdschee** [comment]
> Is there a specific reason why this is not supported?

It is not supported, because the code does not do joins, but applies the security model on each table read and stitches the results together (like a left join does).

Without the security model you end up with something like https://www.pathql.org

PathQL is much better (faster, simpler) and more versatile than TreeQL, but does not apply a security model on the data (you need to define that in the database).

Maybe you can combine the two solutions?

**Comment by Dherlou** [comment]
Thanks for the explanation. I see why this is not possible now.

A **combination** would not work, because:
- **solution 1**: the two queries would have to be done at the API-side due to security reasons, which means I would have to 'hack' the whole 1 SQL-Query per 1 HTTP-Request architecture of this API
- **solution 2**: multiple tables have to be filtered at the same time, so it does not matter which my starting table is

I did a bit of brainstorming and came up with **possible mitigations/solutions**:
- **narrow down the list by filters on the main table**: in our case it could be sufficient to not display a whole list of entries, but only entries that can be filtered with filters on the main table, e.g. "only show children OUs whose parent OU is XYZ" to narrow down the long list and therefore not needing pagination
- **use redundant columns on the main table**: it would be possible to add redundant columns to the main table, which somehow replicate the data of the joined tables, which you want to filter, but this would require to keep  these columns in sync with the 'original' data
- **writing an own middleware for pagination**: it should work to write a middleware that first executes a raw SQL query against the database, which e.g. could return all IDs of persons that the current user is allowed to see regarding our policy, and then manipulates the request to only load the allowed records via batch read

Additionally, it will (as always) be useful to utilize caches so that even if you have to bite the bullet to load the complete list of records to modify it later on the client-side, only the first query will take a while and subsequent (re)loads will be served from the client's cache without needing to perform another heavy query.

**Comment by apps-caraga** [comment]
Just an opinion. If your use case requires a join that is consistently used or needed, maybe its  better to join the tables on the DBMS side and expose it as a view, instead of dynamically building thru the api. This way, the view can be accesses thru the `api.php/records/` endpoint and the filter will work as-is.

**Comment by Dherlou** [comment]
Thanks for the tip. I'll keep it in mind in case we have related performance issues at some point.

It would require us to restructure the client parsing though, because the tables would not be returned nested, but flat.
Additionally, I don't think it would solve our pagination issues. If the view returns the data like this

| personality_pk  | personality_attr | ou_pk | ou_attr |
| ------------- | ------------- | ------------- | ------------- |
| A  | F  | X | M
| A  | F  | Y | O
| B  | G  | Z | N
| C  | H  | X | M

and I would like to use a pagination over the personalities (after they are filtered by the visibility attributes) with a batch of 2, it would only return the rows of personality A, because the person is in a 1-to-2-relationship.
What you would normally do is use a `DISTINCT`, but as far as I know TreeQL does not support this as well.

**Comment by mevdschee** [comment]
@Dherlou Thank you for your explanation. I understand that there are features that one may miss in this software. I think I also understand the cases in which it would be good to have real joins.

>I would have to 'hack' the whole 1 SQL-Query per 1 HTTP-Request architecture of this API

There is no such architecture. There are multiple queries per http request (when you use joins) and all queries respect the security model. There are no filters, nor pagination on nested objects. Filters on nested objects should do a natural join (I guess that is what you are after) while the filters in the security model apply a left join. This difference is one of the problems you run into when implementing this.

My opinion is that once you need complex queries and need more or less full SQL freedom you might as well apply your security model in the database and send SQL to the endpoint. This is where the idea of PathQL was born, see https://www.pathql.org 

NB: PathQL returns nested json and is very much comparable with solutions like GraphQL.
