### ISSUE TITLE
Soft Delete

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#130]
Using the  php-sp-api can we setup to do a soft delete for the data records?

**Comment by mevdschee** [comment]
Soft delete is just a update with a 'datetime' field named 'deleted' set to the current date, isn't it? What do you want to achieve?

**Comment by ubergeekzone** [comment]
Not Exactly,  Take a look at this

--------------------------
id     title                deleted
1      my book         1
2      i'm a coder     0
--------------------------

0 = no deleted, 1 = deleted

Instead of deleting the record form the db, we use a boolean value of 0 for active and 1 for not deleted, I could use an update to do this, sure. But would be awesome if i could alter the delete maybe with a parameter or even extended into the DELETE function to allow this.

**Comment by mevdschee** [comment]
I appreciate your explanation and understand the use case. Still I'm not sure this is a good addition, nor am I convinced that using a boolean is the way to go. I'll leave this item open for further discussion (and upvotes).

**Comment by ubergeekzone** [comment]
@mevdschee check out https://laravel.com/docs/5.3/eloquent#soft-deleting, i see they are using date to do this and not a boolean, I like the date method better seems more interactive. This could easily be done using a PUT, but just make more sense to have it be part of the DELETE. 

It's just an idea to ponder on, thanks!

**Comment by mevdschee** [comment]
You can now use the 'before' handler to implement soft delete.

**Comment by VyseExhale** [comment]
Im struggling to implement the soft deletion .

It seems that the before handler is never called when sending a DELETE

[on rule 1878 of the api.php file](https://github.com/mevdschee/php-crud-api/blob/272f5759f4f09fccc2e2ec3ff73bd7482c254e46/api.php#L1878-L1895) you check if there is any post data sended with the request
'''php
if (strlen($post)) {'.... }
'''

since there is no post data on calling a DELETE, the before handler will never be called.

**Comment by mevdschee** [comment]
@VyseExhale I verified that and will fix that later today.

**Comment by VyseExhale** [comment]
awesome, thx
