### ISSUE TITLE
Output sanitizer

### ISSUE THREAD

**Issue by mnicic** [mevdschee/php-crud-api#161]
It would be nice to take control over output values (on reading action).
For example, I want to return base64 instead of image file location on a server, or to add a prefix to some values.

**Comment by mevdschee** [comment]
Would you also want to add fields? Or just transform the contents?

**Comment by mnicic** [comment]
Good observation - it might be very useful.
Thanks for including this issue on the list.

**Comment by karllhughes** [comment]
I've been thinking about this one too. It seems that if you wanted to take this project in a bigger direction, you could add "hooks" in various points of the cycle allowing devs to write custom code that transforms input/output.

The most obvious places to put hooks to me are:

- After the request enters the app, but before it is sent to the database.
- After the response is generated by the query before it is sent to the requester.

Since this is such a micro-framework, I'm not sure if you want to go that direction or not, but it is an interesting idea.

**Comment by mevdschee** [comment]
>add "hooks" in various points of the cycle allowing devs to write custom code that transforms input/output.

I like that idea.

**Comment by mevdschee** [comment]
@karllhughes I implemented the 'before' and 'after' hooks as you described, but I'm afraid that it may not facilitate the need expressed in this request.

**Comment by mevdschee** [comment]
In v2 there is now "custom" middleware that allows for this use-case using the 'before' and 'after' hooks as you described (also on 'list' operations).
