### ISSUE TITLE
Order/sort by two columns?

### ISSUE THREAD

**Issue by lomboboo** [mevdschee/php-crud-api#162]
Thank you for great work on this project. I have a question: currently I'm using ordering like this: 
`?order=postOrder,asc` . 
But I actually need to include one more column to order by. For example something like: 
`?order=postOrder,asc&order=createdAt,desc`.  
Can it be achieved somehow?

**Comment by mevdschee** [comment]
>Can it be achieved somehow?

No.. it (currently) can't.

**Comment by mevdschee** [comment]
Should work now.

**Comment by ShamimIslam** [comment]
@lomboboo 

Funny. I implemented this feature on April of 2016 along with a few others. Requested a merge. Got shot down. Then your request the same feature but doesn't post a solution 15 days ago. 

@mevdschee turns around and implement the solution within 15 days. What gives? Should I have just complained? I don't think I insulted anyone at the time of? 

@mevdschee 
 
I still feel HTTP operations should be about the HTTP traversal (GET and POST should always mean send visible or send invisible and PUT means I'm sending a file, not payload. HTTP should not be mapped to SQL operations - it makes the understanding of the HTTP operation difficult since HTTP has specific protocol requirements and subverting them to something else means you should be using a new protocol spec - maybe called it SQL://?)

This is what I truly feel is the issue with this library. HTTP should mean HTTP. It should not mean something special. When WebDav extended HTTP, they changed what PROPFIND and other semantics meant because they were speaking webdav:// and no longer http:// - just like Mysql uses mysql:// and so on. Otherwise, this library is very useful, but it makes certain assumptions about how the data should be sent. The [] feature of PHP has long been deprecated as a way to send an array of items through as it is easy to inject harmful code into those constructs. There are other ways to pull data as a single item that can then be split, but again, that's my 40 years of experience talking.

It's your library as you stated before, and it can be forked. Which I did back in April. Great advice. Thanks!

Cheers.

@lomboboo my version is here - have a look - see if you like anything in there. https://github.com/ShamimIslam/php-crud-api

**Comment by mevdschee** [comment]
Thank you (again) for your contribution, I did not mean to offend you in any way.

>I don't think I insulted anyone at the time of?

I'm genuinely sorry that you feel that way, you certainly did not.

>HTTP should mean HTTP. It should not mean something special.

I can agree to disagree on this, but please note that I really appreciate that you you took the time to explain your point-of-view to me.

Kind regards, Maurits
