### ISSUE TITLE
Run tests against implementations in other languages (e.g. C#)

### ISSUE THREAD

**Issue by mevdschee** [mevdschee/php-crud-api#230]
When we refactor the tests it would be great to also be able to run the tests against other implementations (for instance the C# port).

This would allow people to verify that their implementation (port) of php-crud-api is complete.

**Comment by mevdschee** [comment]
See: https://github.com/mevdschee/data-api-dot-net

**Comment by karllhughes** [comment]
So the goal would be to run the same PHPunit test suite on the ports of this framework? Or to port the test suite to those languages too?

**Comment by mevdschee** [comment]
@karllhughes I'm not sure.. an automatic conversion would be a good compromise I think. The goal would be to only support one test suite, so that we can easily see which ports are feature complete.

**Comment by karllhughes** [comment]
I think it would be _possible_ to run an acceptance test suite written in PHP on ports to this API, but you'd have to treat the ported code as a "black box," meaning the test suite can't really see what's happening internally. I don't know if that's going to make much sense though, because then if you get C# devs working on the port, they would also have to know PHP to maintain the test suite.

Maybe a simpler solution to the test suite issue would be to maintain a central checklist of tests that each port should implement? That way when you write the port, you wouldn't forget which tests you needed before you released it.

**Comment by mevdschee** [comment]
Yes, I think you are right. We should just number and/or name the tests and port the test suite to other platforms. Also because every platform has it's own unit/functional testing tools.
