### ISSUE TITLE
Full support for PATCH method

### ISSUE THREAD

**Issue by karllhughes** [mevdschee/php-crud-api#319]
Just curious, but I really like using PATCH requests to update one or two fields at a time since they don't rewrite the whole object like PUT does. I see that this library supports PATCH for atomic increments, but is there any interest or ability to support PATCH in general?

I may start looking into it, but I wanted to ask about it in case you've already done some research on the topic and found it to be hard or impossible to support.

**Comment by mevdschee** [comment]
>I really like using PATCH requests to update one or two fields at a time since they don't rewrite the whole object like PUT does.

Did you verify that? I think PUT is capable of partially updating the record.

**Comment by karllhughes** [comment]
Oh interesting. I have not tried it, I just assumed the PUT method only replaced the entire resource (as [this conversation talks about](https://stackoverflow.com/questions/24241893/rest-api-patch-or-put)).

I'll try it and update this issue accordingly. Thanks!

**Comment by mevdschee** [comment]
The point is that replacing an entire record does not make that much sense when you are thinking about SQL operations. You would rarely do such a thing. Also certain fields identify the object and it would have a mandatory value. Allowing PUT to partially update a record does not prevent you from fully updating a record (although certain databases doe not allow you to update the primary key). Thus, I chose to support partial updates on PUT, also because I mapped the PATCH record to allow for incrementing counters, see: https://github.com/mevdschee/php-crud-api#atomic-increment-for-counters

I hope this makes things more clear.
