### ISSUE TITLE
Unable to PUT when url has Filters

### ISSUE THREAD

**Issue by MrStupidQuestions** [mevdschee/php-crud-api#337]
Hello

I have a Dojo Enhanced Grid which I populate data via JsonRest store and when using the target url as `http://localhost/api/api.php/invoices?filter=month,eq,February 2018` I am able to GET & POST but not PUT.

I am only able to PUT if I remove the ?filter=month,eq,February 2018 from the url.

Is there any settings in the api.php I can change?

Any help will be apprecaited.

Thanks

**Comment by mevdschee** [comment]
@MrStupidQuestions This may be a bug.

**Comment by ankithkonda** [comment]
@mevdschee Hi any update on this? 

I managed to solve the issue by  checking if $key is false at updateObject function on line 1562 -

`protected function updateObject($key,$input,$filters,$tables) {

		

		if (!$input) return null;
		$input = (array)$input;

		$table = $tables[0];
		$sql = 'UPDATE ! SET ';
		$params = array($table);
		foreach (array_keys($input) as $j=>$k) {
			if ($j) $sql .= ',';
			$v = $input[$k];
			$sql .= '!=?';
			$params[] = $k;
			$params[] = $v;
		}

		//MADE CHANGE HERE check if $key is false
		if($key){
			$this->addFilter($filters,$table,'and',$key[1],'eq',$key[0][0]);
			$this->addWhereFromFilters($filters[$table],$sql,$params);
		}

		$result = $this->db->query($sql,$params);
		if (!$result) return null;
		return $this->db->affectedRows($result);
	}
`

Is this what the issue is? I tried to go further up the function call chain and could see that key is being set to false, but I'm not sure why or how.

**Comment by mevdschee** [comment]
@MrStupidQuestions PUT and PATCH can only be applied to a specific record, not to a list of records. While GET can be applied to both (to get and individual record or the list) and POST can only be applied to the list (to add a record).
