### ISSUE TITLE
Allow GET only

### ISSUE THREAD

**Issue by painos** [mevdschee/php-crud-api#510]
I want only allow GET method is the following the best way to go?

```
    'authorization.tableHandler' => function ($operation, $tableName) {
        return ($operation == "list" || $operation == "read");
    },
```

With other methods the message is now  something like Table 'items' not found. Is there a better way to only allow certain operations?

**Comment by mevdschee** [comment]
Because the handler is used both for primary tables and included tables, it is implemented by removing them from the reflection model. This is why the error not found is given. Which is required in cases it is sensitive to expose the existence of certain tables. You could argue that other use cases would benefit more from a "access denied" error.

**Comment by painos** [comment]
OK! This will do fine. 

Thank you for this awesome project! It really has been an important part in many of my projects in the recent years and made my life so much easier. Also seems to be getting constantly better and better.

**Comment by mevdschee** [comment]
Thank you for your feedback. I really appreciate your kind words!
