### ISSUE TITLE
Support for bpchar field type for pgsql

### ISSUE THREAD

**Issue by aalgorry** [mevdschee/php-crud-api#549]
Hi, I detect that the API doesn't support bpchar field type using the driver pgsql.

**Comment by mevdschee** [comment]
Thank you for this issue. I've added interpretation of bpchar as char. Please let me know whether or not this works for you.

**Comment by lnjuanj** [comment]
Hi,
I downloaded the latest master commit and when I build api.php, there is a line that changes compared to the original api.php:
![image](https://user-images.githubusercontent.com/1185991/59358621-309ab200-8d2d-11e9-9fb9-0ac038081dfd.png)
I see that it is related to the commit for this issue. Is the rationale behind the updates on the repository related to api.php?
@aalgorry should know that it is mandatory to build a new api.php in order to try the bpchar functionality in any case.

**Comment by aalgorry** [comment]
Thank you, I will try it and let you know asap if it is working.

**Comment by mevdschee** [comment]
Thank you @lnjuanj for clarifying the modification.

**Comment by aalgorry** [comment]
It's working fine for me. thank you.

**Comment by mevdschee** [comment]
>It's working fine for me. thank you.

Thank you for reporting your success. Enjoy the software!
