### ISSUE TITLE
Database authentication - help

### ISSUE THREAD

**Issue by DariuszPowroznik** [mevdschee/php-crud-api#591]
Hi,
I'm trying to implement database authentication. I add table with users and I added basic configuration from https://github.com/mevdschee/php-crud-api#user-content-database-authentication. Now I have  "code": 1011 so configuration seems to be ok.

But now I want to build login window on frontend part (I'm trying build small frontend application based on Reactjs). I tried to send request 
on http://localhost/api/api.php/login with data (from table users):
`{
    username: "admin"
    password: "password"
}`
to authenticate, but I have code 1011. What else should I add/configure to make it working?

**Comment by lcuis** [comment]
Hello Dariusz.

I made the database authentication work on a Flutter implementation based on this post:
https://stackoverflow.com/a/53991733/2590508
The idea for me was to reuse the authentication cookie received by the login call and send it back for the following calls.

Do you get the `1011: Authentication required` error when you POST on /login or does this happen on your second call?

**Comment by DariuszPowroznik** [comment]
Thank for answer.
It happened when I POST on /login.

**Comment by lcuis** [comment]
No worries, I hope I can help.

Here is a small checklist for database authentication when no customization is done (like [specifying the users table alternative for example through `dbAuth.usersTable` configuration](https://github.com/mevdschee/php-crud-api#middleware)):

1) Your authentication table is `users`?
2) Your user name column is `username`?
3) Your password hash column is `password`?
4) The password hash stored in the database corresponds to the output of `php -r 'echo password_hash("pass2", PASSWORD_DEFAULT)."\n";'`?

**Comment by DariuszPowroznik** [comment]
Yes. Now I see that message has been changed (like in attachement) to "Authentication failed for ''.
I have password without hash (to test purpose).
I add screanshots of my users table and postman request.

Second question from me will be where should I add this code:
`'authorization.tableHandler' => function ($operation, $tableName) {
    return $tableName != 'users';
},`

I tried under 'middlewares' => 'cors,dbAuth,authorization', but I have error.

![code](https://user-images.githubusercontent.com/23011586/68463179-5bbafc00-020e-11ea-85e0-e2b8126cc3f6.jpg)
Database:
![database](https://user-images.githubusercontent.com/23011586/68463181-5bbafc00-020e-11ea-83ef-153b9b726e29.jpg)
Postman:
![postman](https://user-images.githubusercontent.com/23011586/68463182-5bbafc00-020e-11ea-8727-404d7ff96580.jpg)

**Comment by lcuis** [comment]
Hello,

1)
Well, I have good news for you Darek, the password stored like that is not likely to work, it really should be a hash for the authentication to work. Thus, this may be the way to solve your issue.

I would suggest you to try with this hash for `password` for example:
```
$2y$10$PYebk9v7i5lgxHDMZzuEveYAYkPnZaU6/MkJryMjgoA/tjfabRrSC
```

However, when I tried to put "password" instead of its hash in my database, I got a different error message than yours:
```
{
    "code": 1012,
    "message": "Authentication failed for 'admin'"
}
```
As you can see, for me, the username is displayed in the error message. could this be because of other configurations you used that I don't have? I have configurations for:
- username
- password
- database
- debug
- middlewares
- authorization.tableHandler
- authorization.columnHandler
- authorization.recordHandler
- validation.handler
- dbAuth.mode
- dbAuth.usersTable
- dbAuth.usernameColumn
- dbAuth.passwordColumn
- dbAuth.returnedColumns
- sanitation.handler

If using the hash doesn't solve your issue, I would suggest you to temporarily try commenting out some configuration lines that are in your configuration and not in mine.

2) I placed `authorization.tableHandler` at the same place you did, right after middlewares and it works for me. Does this give you a different error message than the authentication one?

**Comment by mevdschee** [comment]
@lcuis, I fully agree. Any feedback @DariuszPowroznik?

**Comment by lcuis** [comment]
Thanks @mevdschee !

@DariuszPowroznik , I just noticed that your first post contains json with `username` and `password` without double quotes `"` around them. This fails for me as well with the exact same error as the one in your last message (without the username). The double quotes around the `"username"` and `"password"` are important for php-crud-api to receive them.

```
{
  "username":"admin",
  "password":"password"
}
```

Maybe this was the reason why you had a different error message than mine while I was trying a password stored directly without hashing?

**Comment by DariuszPowroznik** [comment]
Sorry - I was off for last two days.
I have the same error. Maybe because when I add "authorizationtableHandler" it throws me error like on screenshot:
My config settings:
![config](https://user-images.githubusercontent.com/23011586/68602187-31836b80-04a6-11ea-8171-886f9f67e41f.jpg)
Error with "authorizationtableHandler":
![error](https://user-images.githubusercontent.com/23011586/68602195-33e5c580-04a6-11ea-9244-0f08e8822fa1.jpg)

Line 10214 is "private $values = [". I don't have this error when I remove 'authorization.tableHandler'

**Comment by lcuis** [comment]
Hello Darek,

Thanks for your feedback. No worries for the delay. I am sorry, I don't know why this error is happening really. Maybe @mevdschee will have an idea?

Does this mean that you solved your initial issue with the authentication when you remove the `tableHandler` configuration?

**Comment by DariuszPowroznik** [comment]
No. I still have this error. I tried to add extra configs: 
`           'dbAuth.usersTable' => 'users',
            'dbAuth.usernameColumn' => 'username',
            'dbAuth.passwordColumn' => 'password',`
But it didn't help.

Is it possible that It's not working because of 'authorization.tableHandler'?

**Comment by lcuis** [comment]
When I have an error related to the `tableHandler`, it doesn't look like a problem with the authentication.

I was wondering whether your return in the `tableHandler` configuration could be the reason for the error as it returns false on any operation on the `users` table but all is fine for me when I use an equivalent code (I have another name for the user table in fact):
```
if($tableName=="users")
return(false);
```
If the error message you get when there is no `tableHandler` configuration is the following one:
```
{
    "code": 1012,
    "message": "Authentication failed for 'admin'"
}
```
Then, maybe there is something wrong with the way you store the password hash in the database?
However, when I try with a faulty hash myself and the exact same `tableHandler` as you, I don't have your error message but the one just above this paragraph.

I didn't see the `customOpenApiBuilders` configuration mentioned in the [readme](https://github.com/mevdschee/php-crud-api) documentation.
This makes me wonder whether you are maybe trying to edit the wrong place in the configuration. I edit the very end of the file for configuration. Somewhere where it starts like:
```
$config = new Config([
```
Yes, it looks like this could be the root cause of your issues.

**Comment by DariuszPowroznik** [comment]
You were right. I puted configs in the wrong palce in code. I fixed it - now 'authorization.tableHandler' does not crash. But still POST to /login returns:
`{
    "code": 1012,
    "message": "Authentication failed for ''"
}`
I'm wondering why there is no "admin" user but only empty string...

Current confing:
![config](https://user-images.githubusercontent.com/23011586/68606947-d35b8600-04af-11ea-8ec2-c6ec899e1493.jpg)
Database user:
![database](https://user-images.githubusercontent.com/23011586/68606978-e79f8300-04af-11ea-9b77-d937917076fd.jpg)

**Comment by lcuis** [comment]
Indeed, the fact that `admin` is absent from the error message is surprising.
Do you have the same result (without `admin` in the error message) in case you remove the `tableHandler` configuration?

**Comment by DariuszPowroznik** [comment]
Yes. I have the same message without 'admin'.

**Comment by DariuszPowroznik** [comment]
Ok. I reloaded postman and apache and now I everything works fine! As result I have user date from database. Thanks very much for help!

I have one more question - is there posibility to gain token ID for frontend authorisation?

**Comment by lcuis** [comment]
What I can see from the `php-crud-api` code is that this error message can come without a user name in a POST on `/login` from the last of the following lines:
```
            if ($method == 'POST' && $path == 'login') {
                $body = $request->getParsedBody();
                $username = isset($body->username) ? $body->username : '';
                $password = isset($body->password) ? $body->password : '';
                $tableName = $this->getProperty('usersTable', 'users');
                $table = $this->reflection->getTable($tableName);
                $usernameColumnName = $this->getProperty('usernameColumn', 'username');
                $usernameColumn = $table->getColumn($usernameColumnName);
                $passwordColumnName = $this->getProperty('passwordColumn', 'password');
                $passwordColumn = $table->getColumn($passwordColumnName);
                $condition = new ColumnCondition($usernameColumn, 'eq', $username);
                $returnedColumns = $this->getProperty('returnedColumns', '');
                if (!$returnedColumns) {
                    $columnNames = $table->getColumnNames();
                } else {
                    $columnNames = array_map('trim', explode(',', $returnedColumns));
                    $columnNames[] = $passwordColumnName;
                }
                $columnOrdering = $this->ordering->getDefaultColumnOrdering($table);
                $users = $this->db->selectAll($table, $columnNames, $condition, $columnOrdering, 0, 1);
                foreach ($users as $user) {
                    if (password_verify($password, $user[$passwordColumnName]) == 1) {
                        if (!headers_sent()) {
                            session_regenerate_id(true);
                        }
                        unset($user[$passwordColumnName]);
                        $_SESSION['user'] = $user;
                        return $this->responder->success($user);
                    }
                }
                return $this->responder->error(ErrorCode::AUTHENTICATION_FAILED, $username);
            }
```
The `$username` there is set by this line:
```
$username = isset($body->username) ? $body->username : '';
```
So, in your case, it really looks like your `username` is not set in your `/login` body.
In order to understand better what is happening, can you please place the following echo line at this location right after the `$body` is assigned?
```
            if ($method == 'POST' && $path == 'login') {
                $body = $request->getParsedBody();
echo("body: ".print_r($body,true));
                $username = isset($body->username) ? $body->username : '';
```
Then call the `/login`. In my case, this displays the following with an intentionally faulty password in the database:
```
body: stdClass Object
(
    [username] => admin
    [password] => password
)
{"code":1012,"message":"Authentication failed for 'admin'"}
```

**Comment by lcuis** [comment]
Oh, great to read that it works fine. You are welcome.

For the token ID, I just take the cookie sent by the server at the `/login` POST and return it on every call. If this doesn't answer your question, as you may not consider this as a token, you may want to ask @mevdschee .

**Comment by DariuszPowroznik** [comment]
I see. It's resolve all my problems for now.
Thanks so much for helping me!

**Comment by lcuis** [comment]
My pleasure!
