### ISSUE TITLE
Authorization Token with dbAuth

### ISSUE THREAD

**Issue by billiemead** [mevdschee/php-crud-api#661]
Hello, I am fairly new to programming and I apologize in advance for having to reach out for help, but I have tried on my own for just about 2 weeks now. And while I have learned a great deal more about Laravel and authorization in general, I am stuck.

I'm trying to integrate w Laravel 5.8 to build an API that mobile devices can connect to and have been using the Appgyver.com platform Composer to build the mobile platform. Its a low-code platform built on the React platform and I have been trying to figure out how to read the PHP session cookie once a user has been authorized and on each subsequent request. 

After trying several solutions and not being successful I posted on their help forum and this was the response I received:

"So the response for the successful authentication from your backend comes with a cookie instead of an authorization token? That’s a not-very-API way to do it, and Composer currently doesn’t support a cookie-based session flow out of the box. Is it possible to change your API to return a token instead that could be then sent as part of e.g. an Authorization header on subsequent calls?"

I'm sure the obvious answer is to switch authentication method from dbAuth to jwtAuth but before I do I wanted to ask if I could accomplish authorization token based authentication using dbAuth and if that was even recommended? And I'm not asking how to do it (I'll figure that out on my own) just if its even recommended and maybe a pointer in the right direction?

Thank you in advance for helping me on my journey! It's been a really fun 12 months but can be a little overwhelming at times.

**Comment by mevdschee** [comment]
>I am fairly new to programming and I apologize in advance for having to reach out for help

No need to apologize, thank you for taking the time to create this issue.

>I'm trying to integrate w Laravel 5.8 to build an API that mobile devices can connect to

This is a specific use case that many people have.

>That’s a not-very-API way to do it

Let's say that there are pros and cons and that your choice may depend on your use case.

>I'm sure the obvious answer is to switch authentication method from dbAuth to jwtAuth

Indeed, they both use different methods of establishing a session (relating requests).

> if I could accomplish token based authentication using dbAuth and if that was even recommended

No dbAuth is cookie based, while jwtAuth is token based. 

>And I'm not asking how to do it (I'll figure that out on my own) just if its even recommended and maybe a pointer in the right direction?

First of all: this is a very important and much debated subject and I'm not picking sides.

These are the characteristics of each method:

- (session) cookies can be 'httpOnly' and 'secure' and will be protected against XSS.
- JWT based tokens can be passed cross domain, because the proof of their authenticity is in a signature and not the domain they relate to. On the other hand they can easily be stolen in case of an XSS vulnerability.

Therefor IMHO interactive login (on a login page) makes more sense with session cookies, while authentication that is transferred from an external identity provider makes more sense with JWT. The identity provider (Auth0 or Firebase for example) uses tokens to transfer the proof of authentication (cross domain or not) to the API.

I feel your use-case would benefit most from social login (such as facebook) through Auth0 or any other provider combined with JWT based authentication using the jwtAuth middleware.

You may use [php-api-auth](https://github.com/mevdschee/php-api-auth/) as a starter project to implement your own identity provider (if you don't want to use Auth0 or Firebase).

I hope this helps. Kindest regards, Maurits

**Comment by billiemead** [comment]
> I hope this helps. Kindest regards, Maurits

Maurits, your guidance has been invaluable and so appreciated. In fact, I will never forget it and can't wait until I can pass it along to the next up-and-coming programmer.

I knew you had very solid reasons for going with cookie based authentication and because there are so many mixed options out there, it can be confusing. But as you are the software author, this means all the more.

> I feel your use case would benefit most from social login (such as facebook) through Auth0 or any other provider combined with JWT based authentication using the jwtAuth middleware.

I am going to go with your suggestion and actually cant wait to get started! And I know there is a lot on the subject here and in other open and closed tickets.

Maurits, Please take care for now and I hope you are yours are staying safe! Kind regards, Billie

**Comment by mevdschee** [comment]
Thank you for your kind words, they mean a lot to me. Enjoy the software!

**Comment by gasalvati** [comment]
@billiemead / @mevdschee 
hello, hope you have time to give me a hint. (Big one).
I'm posting this in this closed issue because is the same concept, but I can open a new one if is the right way.

I'm doing a very basic Appgyver app (mobile) for dealing with my data in a PHP/MySql backend.
I'm using apì.php from @mevdschee  and got it to work decently. (By the way excellent job and thanks to Maurits).
I'm bad at OOP but have some experience in procedural php (so I can follow the procedural part and do some minor changes)
Now, my next goal is to have the app secured, We will be no more than four users (me and my brothers reach to three and one spare) but as an exercise I'm doing it with a db users table (without roles up to now).
Because being an Appgyver monile app I can´t rely on cookies for authentication (that took off dbAuth from the equation), and seems that token based authentication is my way. I do not like the idea of a static ApiKey.
The options I'm looking at are jwtAuth and apiKeyDbAuth. Searching at the forums lead me to (also @mevdschee ) auth.php.
At his point I reached @billiemead old post.
So, as I read, auth.php with jwtAuth in api.php can be a solution. 

1-Can I use these combination (auth.php+api.php with jwtAuth) without cookies at the mobile app front-end?
    I have seen that auth.php use session_start (maybe this session only travels auth.php<->api.php without reaching the mobile app)

2-Am I right thinking that my app will point to (post/get) auth.php instead of api.php (and auth.php will redirect to api.php)?
   I understand that I have to configure audience var in auth.php with value 'api.php' to do so. And have to point my front-end app to this new endpoint (adding auth.php in my previous endpoints paths, prior to api.php : example _https://mydomain/..../auth.php/api.php/..._)

3-Whats the _client_id_ concept in auth.php? Can I use one default for dealing with all my 4 users (expecting this), or I have to prearrange one _client_id_ for every db/app user? Is this _client_id_ the same that my db table _user_id_?

4-I wiil be able to redo the validate user function in auth.php (no clean OOP, just legacy procedures) with a connection to my db and searching my user to be verify.
This way the cookies will be between the php programs and auth.php will connect front-end app and api.php with a token?
Is this the right way?

5-@mevdschee , in this post you say :
_"You may use [php-api-auth](https://github.com/mevdschee/php-api-auth/) as a starter project to implement your own identity provider (if you don't want to use Auth0 or Firebase)."_
But in php-api-auth
_"I suggest that you first get PHP-CRUD-API working with [Auth0](https://auth0.com/) before you start implementing your own JWT based authentication provider using this repository."_

6-@billiemead , do you have any progress with this that you mind to share?

That's all up to now
Sure if you can answer I'll have more doubts, but that's gonna be a problem for the future me.

Thanks a lot
GS
