### ISSUE TITLE
info : js-crud-api, a library for accessing php-crud-api

### ISSUE THREAD

**Issue by thipages** [mevdschee/php-crud-api#770]
Hi,

I just publish [js-crud-api](https://github.com/thipages/js-crud-api)
It is a rather small library sticking as much as possible with php-crud-api formalism.

Any feedbacks are welcome.

**Comment by mevdschee** [comment]
I've added a link to the README.. let's see whether or not people start using it.. fingers crossed!

**Comment by thipages** [comment]
Hi,
First, thanks for sharing JS-CRUD-API on PHP-CRUD-API readme.

Also, I would like to share some lessons learned/remarks I got during the development of the JS lib
Hope I go through issues enough and not missed related items.

 1.  `include ` filters restricts fields but not FK fields
 2.  Invalid filters (eg `sizee `instead of `size`) are discarded, this leads to unexpected results during tests!!. Implementing a strict mode option may be useful
3. /register does not log in. This requires a two steps operation : this could be useful as an option (`'dbAuth:autologin' false/true`)
4. DBAuth password has a size limitation only. Could be interesting to replace it by a default regex like /^.{6,12}$/ 
5. list and read operations allowed filters is unclear in the PHP-CRUD-API documentation (neither in mine...). I may propose you a table for clarification (need first to clarify my tests)
6. side note : transversal joins could not be implemented as in PHP-CRUD API (join=table1,table2&join=table3). It has been implemented as {join:'table1,table2',join1:'table3'} close to the OR filter formalism (filter, filter1, ...)


Anyway that was fun!
Thank you for your great lib!!

**Comment by mevdschee** [comment]
I'll try to comment on each of the points.

> 1) include filters restricts fields but not FK fields

Fields that are used in the joins cannot be excluded due to the order of evaluation.

> 2) Invalid filters (eg sizee instead of size) are discarded.. Implementing a strict mode option may be useful

Agree, this would be a good idea even as a default.

> 3) Implementing a strict mode option may be useful

I'm not sure this really matters as you are automating the process anyway, aren't you? Anyway I would merge a PR that adds this functionality.

> 4) DBAuth password has a size limitation only.

True, but a maximum length does not make any sense.. or does it? Also restricting the format is a bad idea, because of random password generators.

> 5) list and read operations allowed filters is unclear in the PHP-CRUD-API documentation

Feel free to propose improvements of on the documentation.

>6) side note : transversal joins could not be implemented as in PHP-CRUD API

GET parameters can be repeated, so a proper reflection of those options would be:

{join:[['table1','table2'],['table3']]}

instead of:

{join:['table1','table2'],join1:['table3']}

I hope these responses help you. Thank you for your great client library! Kind regards, Maurits

**Comment by thipages** [comment]
Thanks for you clear reply

> 3. /register does not log in. This requires a two steps operation
> I'm not sure this really matters as you are automating the process anyway, aren't you?
> Anyway I would merge a PR that adds this functionality.

yes it can be automatized, but it is much more dev friendly (from a js point of view) 

>  4. DBAuth password has a size limitation only.
True, but a maximum length does not make any sense.. or does it?
Also restricting the format is a bad idea, because of random password generators.

regex will allow dev to customize passwords according to their own security rules. /^.{12,1000}$/ as default should be enough for max length.

> {join:[['table1','table2'],['table3']]}

Missed it. Good point. May work for OR filters too. Will try with real use cases before changing. Thanks!
