### ISSUE TITLE
JSON Middleware filtering

### ISSUE THREAD

**Issue by ndee85** [mevdschee/php-crud-api#793]
Hi,
I wanted to work with json datatypes in my mysql database to gain better flexibility so I could easily extend data.
I enabled the json middleware and got it to read and deliver the json data as I wish.

My question would be: Can I filter json dataobjects?
Lets say I have this database structure:

Table users:
ID(int)   USER_DATA(json)
1           {"name":"Foo", "age":10}
2           {"name":"Bar, "age":12}
3           {"name":"Hello, "age":12}
4           {"name":"World, "age":12}

I haven't found a way yet to filter my records by lets say "age". Is it possible with the current filter methods?

I tried something like that:

path/api.php/records/users?filter=age,eq,12

But this didn't seem to work, as it is throwing an error. I asume it is looking only for columns name age. Is this possible to filter json datatypes?

**Comment by mevdschee** [comment]
Hi Andreas,

> I asume it is looking only for columns name age.

Indeed it does.

> Is this possible to filter json datatypes?

No, and this is by design. If you want to do something with the contents of a JSON string, then you should let the client deal with it. As far as the database is concerned it is just a json clob, a form of unstructured data.

Structured data with it's structured query language (SQL) is an important concept that should be used whenever possible. This model allows storage and retrieval of unstructured data in strings and those strings can be represented as JSON. That is exactly what is supported and nothing more.

I hope you understand my design decision on this subject, in case you want to understand it better you may read: https://tqdev.com/2020-storing-json-strings-in-mariadb

Kind regards, Maurits

**Comment by ndee85** [comment]
Hi Maurits,
I fully understand. Thanks for taking the time and explaining your reasons. I'll have a read on the subject :-)
Thanks for sharing.
