### ISSUE TITLE
Custom controller to run sql queries

### ISSUE THREAD

**Issue by niyonx** [mevdschee/php-crud-api#810]
Hi I followed [this](https://gist.github.com/akuehnis/d1c305959040d900b059933b73ee0e76) README to create a custom controller with custom routes. 

Would it be possible to execute queries from the custom controller file?

```
$sql = 'SELECT ' . $selectColumns . ' FROM "' . $tableName . '"' . $whereClause . $orderBy . $offsetLimit;
$stmt = $this->query($sql, $parameters);
$records = $stmt->fetchAll();
$this->converter->convertRecords($table, $columnNames, $records);
return $records;
```

Something similar to this would be ideal as I would be able to create custom routes with parameters and do custom sql queries and return its json.

**Comment by zemian** [comment]
Hi @niyonx , I wanted the same here, a custom controller to run a customized query and return result. The problem is that a CustomController will only have `RecordService` param injected, and that itself does not allow you to run custom query. With little hack, I was able to get a hold of the the internal `GenericDB` instance, and used that to run custom query. See example here: https://github.com/zemian/php-crud-api/blob/zemian_my-examples/my-examples/my-custom-controllers-query.php

Hi @mevdschee, what a cool project you got here. I love this minimal php-crud-api, and yet so flexible and useful. It's enough to get me started and exploring many webapp ideas of my own. Thank you for your work! Anyway, same as @niyonx request, I find myself same need here. Would it possible to improve the custom controller so that it can inject other services into custom controller instances such as the `GenericDB`, the `Config`, or even the `Api` instances are useful if one were to make more custom extensions to the app.

**Comment by niyonx** [comment]
Hey @zemian, I was able to do it, I added a method to the generic db, then added a method in the record service which uses the method I created in generic db. Now from the service I receive I'm able to do custom sql queries! Thanks still!
