### ISSUE TITLE
Find Distance Between Two Lat/Long Points Flitter

### ISSUE THREAD

**Issue by ubergeekzone** [mevdschee/php-crud-api#98]
Can you add a way to Find Distance Between Two Lat/Long Points in the flitters? 

Thanks!
Amy

**Comment by ubergeekzone** [comment]
Here is 2 great explanations of mysql we could use, https://github.com/mnisjk/MySQL-distance-between-GPS-coordinates

**Comment by mevdschee** [comment]
Hi Amy,

Check out http://postgis.net

It is unparalleled.

Maurits

**Comment by ubergeekzone** [comment]
I need this to work with MySQL, thanks for the resource though. Could we get this added into the php-crud-api for MySQL?

**Comment by ubergeekzone** [comment]
i got this added into the api myself today, ended up making a new filter called "geo" and attached my geo cords and mile radius to it so it looks like this geo=lat::lng::miles and then just altered the select statement in the API code using an if statement. Works prefectly. 

Thanks!
Amy

**Comment by mevdschee** [comment]
I appreciate your feedback and understand your needs, but the readme states:

>Complex queries calling functions (like "concat" or "sum") are not supported

Since elementary functions are not supported as stated in the readme, these specialized geometric functions (like distance) will also not be supported. You may find the [stored procedure project](https://github.com/mevdschee/php-sp-api) helpful for your use case as you are free to do whatever you want in SQL when you use that.

**Comment by lupohirp** [comment]
> i got this added into the api myself today, ended up making a new filter called "geo" and attached my geo cords and mile radius to it so it looks like this "geo=lat::lng::miles" and then just altered the select statement in the API code using an if statement. Works perfectly.
> 
> Thanks!
> Amy

hi, can you share your solution?
